Fix error handling
Error-handling functions in Express apps take four parameters (err, req,
res, next).[1]  Omitting the 'next' param breaks error handling.

Example:

http://localhost:16535/foo

Expected: "Cannot GET /foo"

Actual: "TypeError: res.status is not a function
    		at app.use (/Users/mholloway/tilerator/lib/util.js:210:9)
    		[...]"

This patch restores the 'next' param and gets error handling working again.

[1] https://expressjs.com/en/guide/error-handling.html#writing-error-handlers